apiVersion: skaffold/v3
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_TAG}}"
  artifacts:
    - image: public.ecr.aws/sctp-sandbox/stephen-flask-crud
      context: backend
      docker:
        dockerfile: backend/Dockerfile
    
      
manifests:
  rawYaml:
    - .k8s/flaskservice-deployment.yaml
        
deploy:
    # In case we enable status check, this will be the timeout till which skaffold will wait
    statusCheckDeadlineSeconds: 600
    # Using kubectl as our deployer
    kubectl: {}
    
        # Location to our yaml files
        # Refer https://skaffold.dev/docs/references/yaml/ for more options
        
